### ISSUE TITLE
Is there a training process in the PNN method?

### ISSUE THREAD

**Issue by Zhang-Jinwei** [codegaj/py_pansharpening#17]
Hello! Thanks for your work very much!
I want to ask you something about the training in the PNN method.When I run the PNN method, I saw the text showing the training in the code, and it finally updated the weight file. But I didn't see any dataset. What is it using for training?

**Comment by codegaj** [comment]
We downsample the original images with a kernel to construct training dataset

**Comment by Zhang-Jinwei** [comment]
Thank you very much for your answer. May I ask pansharpening is generally pan: ms for 4:1 ratio? Can I set other ratios? Like 2:1 or 8:1.I tried, but the code ran wrong.

**Comment by codegaj** [comment]
yes, you can, 4:1 is the most common ratio, like GF1, GF2, WV2
