### ISSUE TITLE
Why we need ''generating ms image with gaussian kernel'' ?

### ISSUE THREAD

**Issue by pjwang317** [codegaj/py_pansharpening#2]
@ codegaj, Hi, 
Thank you for your wonderful work! 
I have one point I do not understand in the demo_all_methods,  '''generating ms image with gaussian kernel'''  why do you used this part as the input of the different kinds of methods? why don't we just use the original ms and pan images?

Thanks in advance for your reply!

**Comment by codegaj** [comment]
because real imaging process obeys Gaussian distribution
