### ISSUE TITLE
Some questions about evaluating indicator

### ISSUE THREAD

**Issue by Randyer-w** [codegaj/py_pansharpening#4]
Thank you very much for your code, it helped me a lot in my experiments. I want to know what the full names of D_lamda, D_s, SCC and SAM in the code. Please tell me，thank you very much!

**Comment by codegaj** [comment]
hello, wanghaorananda, D_lamda means Spectral component of QNR, D_s represents Spatial component of QNR, QNR is also a nonreference metric for pansharpening. And SCC is Spatial Correlation Coefficient, and SAM is Spectral Angle Mapper!
