### ISSUE TITLE
.h5文件

### ISSUE THREAD

**Issue by Songtao-Wang** [codegaj/py_pansharpening#5]
PNN_model.h5和PANNET_model.h5是在哪个卫星上训练获得的？

**Comment by codegaj** [comment]
这个是在处理GF2北京这种图时保存的模型文件

**Comment by Songtao-Wang** [comment]
好的，谢谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;anjing_guo&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月22日(星期一) 下午5:20
收件人:&nbsp;&quot;codegaj/py_pansharpening&quot;<py_pansharpening@noreply.github.com&gt;;
抄送:&nbsp;&quot;Songtao-Wang&quot;<2876754665@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [codegaj/py_pansharpening] .h5文件 (#5)
