### ISSUE TITLE
How to compute Nyquist frequency of different sensors in method of MTF_GLP?

### ISSUE THREAD

**Issue by xjhcassy** [codegaj/py_pansharpening#7]
Thanks for sharing the job. I have a question about How to compute Nyquist frequency of different sensors in method of MTF_GLP?

**Comment by codegaj** [comment]
Hello, the Nyquist frequency of each satellite may be fixed, and you can check the relevant information, there are only some Nyquist frequencies of common satellites in this package. You can also use some spatial blur kernel estimation methods.
